repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        files: \.(cob|COB)$
      - id: trailing-whitespace
        files: \.(cob|COB)$
      - id: mixed-line-ending
        files: \.(cob|COB)$
        args: ['--fix=lf']  # Forces Unix line endings (LF)
      - id: check-added-large-files